module SectionIV.Task7Tests
  ( sectionIVTask7Tests
  ) where

import SectionIV.Task7
  ( Grammar(..)
  , Production(..)
  , Symbol(..)
  , minlengthL
  , solve
  , wordsMinlenL
  )
import TestRunner (Test, assertEqual, testCase, testGroup)

sectionIVTask7Tests :: Test
sectionIVTask7Tests =
  testGroup
    "Section IV, task 7"
    [ testCase
        "direct left recursion"
        (assertEqual (Just 1) (minlengthL directLeftGrammar "A"))
    , testCase
        "direct left recursion words"
        (assertEqual ["a"] (wordsMinlenL directLeftGrammar "A"))
    , testCase
        "indirect left recursion"
        (assertEqual ["bc"] (wordsMinlenL indirectLeftGrammar "A"))
    , testCase
        "empty word recursion"
        (assertEqual (Just 0) (minlengthL emptyWordGrammar "A"))
    , testCase
        "multiple minimal words"
        (assertEqual ["a", "b"] (wordsMinlenL multipleWordsGrammar "A"))
    , testCase
        "no valid recursion"
        (assertEqual Nothing (minlengthL noRecursionGrammar "A"))
    , testCase
        "terminal prefix generated by nonterminal"
        (assertEqual ["c"] (wordsMinlenL generatedPrefixGrammar "A"))
    , testCase
        "suffix after carried nonterminal is blocked"
        (assertEqual [] (wordsMinlenL blockedSuffixGrammar "A"))
    , testCase
        "solve all listed nonterminals"
        (assertEqual [("A", Just (1, ["a"])), ("B", Nothing)] (solve solveAllGrammar))
    ]

directLeftGrammar :: Grammar
directLeftGrammar =
  Grammar
    { ns = ["A"]
    , sigma = "a"
    , ps = [Production "A" [T 'a', N "A"]]
    }

indirectLeftGrammar :: Grammar
indirectLeftGrammar =
  Grammar
    { ns = ["A", "B"]
    , sigma = "bc"
    , ps =
        [ Production "A" [T 'b', N "B"]
        , Production "B" [T 'c', N "A"]
        ]
    }

emptyWordGrammar :: Grammar
emptyWordGrammar =
  Grammar
    { ns = ["A"]
    , sigma = []
    , ps = [Production "A" [N "A"]]
    }

multipleWordsGrammar :: Grammar
multipleWordsGrammar =
  Grammar
    { ns = ["A", "B"]
    , sigma = "abcd"
    , ps =
        [ Production "A" [T 'a', N "A"]
        , Production "A" [T 'b', N "A"]
        , Production "A" [T 'c', N "B"]
        , Production "B" [T 'd', N "A"]
        ]
    }

noRecursionGrammar :: Grammar
noRecursionGrammar =
  Grammar
    { ns = ["A", "B"]
    , sigma = "ab"
    , ps =
        [ Production "A" [T 'a', N "B"]
        , Production "B" [T 'b']
        ]
    }

generatedPrefixGrammar :: Grammar
generatedPrefixGrammar =
  Grammar
    { ns = ["A", "B"]
    , sigma = "c"
    , ps =
        [ Production "A" [N "B", N "A"]
        , Production "B" [T 'c']
        ]
    }

blockedSuffixGrammar :: Grammar
blockedSuffixGrammar =
  Grammar
    { ns = ["A"]
    , sigma = "ab"
    , ps =
        [ Production "A" [N "A", T 'a']
        , Production "A" [T 'b']
        ]
    }

solveAllGrammar :: Grammar
solveAllGrammar =
  Grammar
    { ns = ["A", "B"]
    , sigma = "ab"
    , ps =
        [ Production "A" [T 'a', N "A"]
        , Production "B" [T 'b']
        ]
    }
