name:                 ptp-haskell
version:              0.1.0.0
visibility:           public
id:                   ptp-haskell-0.1.0.0-inplace
key:                  ptp-haskell-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    SectionIA.Task27 SectionIB.Task65 SectionII.Task2 Tasks

import-dirs:
    /Users/tymofii.leitsyshyn/Personal/ptp/ptp-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/ptp-haskell-0.1.0.0/build

library-dirs:
    /Users/tymofii.leitsyshyn/Personal/ptp/ptp-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/ptp-haskell-0.1.0.0/build

library-dirs-static:
    /Users/tymofii.leitsyshyn/Personal/ptp/ptp-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/ptp-haskell-0.1.0.0/build

dynamic-library-dirs:
    /Users/tymofii.leitsyshyn/Personal/ptp/ptp-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/ptp-haskell-0.1.0.0/build

data-dir:             /Users/tymofii.leitsyshyn/Personal/ptp/ptp-haskell/.
hs-libraries:         HSptp-haskell-0.1.0.0-inplace
depends:              base-4.18.3.0
haddock-interfaces:
    /Users/tymofii.leitsyshyn/Personal/ptp/ptp-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/ptp-haskell-0.1.0.0/doc/html/ptp-haskell/ptp-haskell.haddock

haddock-html:
    /Users/tymofii.leitsyshyn/Personal/ptp/ptp-haskell/dist-newstyle/build/aarch64-osx/ghc-9.6.7/ptp-haskell-0.1.0.0/doc/html/ptp-haskell
